### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "e5661f55e77e4401a4b43bd69cf1673a",
  "accountNumber": "1000000002",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/7f75893e55cc49d8a4865dd88aa9861a

